# Introduction {-}

## What is R?{-}

R is a statistical analysis environment initially created and developed by Ross Ihaka and Robert Gentleman in 1996. It can be regarded as an implementation of the S language, which was developed at Bell Laboratories by Rick Becker, John Chambers and Allan Wilks. 

R can be used both as a programming language and as a software package which you can use to manipulate your data, perform calculations, conduct statistical analyses and display graphics. Some advantages of using R include

- R is open source, platform agnostic and freely available. 
- R has an extensive and coherent set of tools for statistical analysis.
- R has an extensive and highly flexible graphical facility capable of producing publication quality figures.
- R has an expanding set of freely available ‘packages’ of routines for special or unusual analyses.
- R has an extensive support network with numerous online and freely available documents.

However, for those who haven’t used it before, R may seem rather daunting and complex. Whilst the initial learning curve is admittedly a little steep, R offers the user a degree of flexibility and control not usually available in other more traditional 'point and click' statistical software. Undoubtedly, the time invested in learning R now will be more than repaid at a later date. Most importantly, learning to use R will change the way you think about data analysis. As your analysis will be implemented using R code and R scripts you will always have a permanent and accurate record of your analytical approach which you can then make available to others to facilitate robust and reproducible research practices. 

## Installing R in Windows{-}

Most people using this guide will be running R on a computer with a Windows operating system (for other operating systems see the next section or the [R-project](https://www.r-project.org/) web site). 

R can be downloaded as a self-extracting file from the Comprehensive R Archive Network (CRAN) [website](https://cran.r-project.org/)

Click on ‘Windows’, click on ‘base’ and then ‘Download R 3.6.1 for Windows’ (the version available whilst writing this guide). Double click on the downloaded R executable file and follow the on screen instructions. Full installation instructions can be found at the CRAN website. Although various contributed packages are now included with the standard R distribution, you may need to install other packages to perform particular analyses (see section 1.8 for details of how to do this).

## Installing R in other operating systems{-}

One of the great things about R is that it’s compatible with many operating systems. You can download the appropriate binary for MAC OSX [here](https://cran.r-project.org/bin/macosx/). On Bio-Linux, the good news is that R is already installed by default so there is no need to do anything! For other Linux distributions you can find installation instructions [here](https://www.stats.bris.ac.uk/R/) and follow the ‘Download R for Linux’ hyperlink.

## Starting R on a University of Aberdeen network PC{-}

First, log onto the University network using your usual username and password. Double click on the Life Science and Medicine folder on the Desktop, then the Biological Sciences folder and finally to the Zoology folder. Shortcuts to both R, and RStudio (more later) should be visible. Double click on either to start the program.

## The R console{-}

In Windows, once you have started R you will see the standard graphical user interface (GUI). In other operating systems the layout will vary, but all the essential elements are similar. The GUI is rather spartan with a limited number of menu and toolbar commands (Figure 1.1).

