# Graphics in R

One of my personal favourite uses of `R` is in making figures. For me, these are either quick dirty plots to allow me to get a feel for what's going on in my dataset, or fancier/more complex figures to use in a publication. This is as close as I get to having an "artistic" streak so I make sure to enjoy making figures when I have the chance.

As stated in the introduction, one of the many reasons for the rise in popularity of `R` is due to it's ability to produce publication standard figures (as well as quick and easy ones). Not only can users make figures well suited for publication, but producing figures in `R` allow lots of customisation, in turn allowing users to create their own particular styles/brands of figures (well beyond the beyond cookie-cutter styles in more traditional click and point programs).

We will focus on two ways to produce figures in `R`. The first will be base `R` figures and the second will be through using a package called `ggplot`.

## Base R data visualisation

Content to be added

## ggplot data visualisation

Before we get going with making some plots of the gg variety, how about a quick little history of the most commonly used packages in R? `ggplot2` was based on a book called _Grammar of Graphics_ (hence the `gg` in `ggplot2`) by Leland Wilkinson (yours for only £100 or so)[https://www.springer.com/gp/book/9780387245447]. But before you spend £100 see (here)[https://www.jstatsoft.org/article/view/v017b03/v17b03.pdf] for an interesting summary of Wilkinson's book. 

Briefly, Wilkinson's idea (one of them anyway) in _grammar of graphics_ was that figures can be broken down into consituent parts, such as layers (more on this later). While Wilkinson would eventually go on to become vice-president of SPSS, his (and his co-author's) ideas would, never-the-less, make their way into R. 

In 2007 `ggplot2`was officially released by Hadley Wickham. By 2017 the package was said to have been downloaded 10,000,000 times. `ggplot2` now has many secondary packages that use it either as a foundation for expanding on or for interfacing (some statistical packages now have accompanying `ggplot2` interfaces for producing figures).

It is important to note here that `ggplot2` is not required to make "fancy" figures. If you'd prefer to ue base R then go ahead. Exactly equivalent figures are possible in base R. The difference between`ggplot2` and base is to do with how you _get_ to the end product rather than any differences in the end product itself. This is, never-the-less, a common belief almost certainly due to the fact that making a moderately attractive figure is easier to do with `ggplot2` as many decisions are made for the user, without you necessarily even knowing that a decision was ever made!

With that in mind, let's get started.

### qplots - the ggplot version of plot()